### ISSUE TITLE
java.net.SocketException: Invalid argument on c.connect

### ISSUE THREAD

**Issue by evan108108** [Sciss/ScalaOSC#8]
Always errors when trying to connect i.e (c.connect())
```
  java.net.SocketException: Invalid argument
  at sun.nio.ch.Net.connect0(Native Method)
  at sun.nio.ch.Net.connect(Net.java:465)
  at sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:738)
  at de.sciss.osc.impl.DirectedUDPReceiverImpl.connectChannel(DirectedUDPReceiverImpl.scala:27)
  at de.sciss.osc.impl.ReceiverImpl$class.connect(ReceiverImpl.scala:45)
  at de.sciss.osc.impl.DirectedUDPReceiverImpl.connect(DirectedUDPReceiverImpl.scala:20)
  at de.sciss.osc.impl.BidiImpl$class.connect(BidiImpl.scala:24)
  at de.sciss.osc.impl.UDPClientImpl.connect(UDPClientImpl.scala:20)
  ... 43 elided
```

Any thoughts?

**Comment by Sciss** [comment]
Can you provide a minimally working example? Without context it's difficult to assess...

**Comment by evan108108** [comment]
Here is an example that returns the error message above:

```scala
import de.sciss.osc._
import Implicits._
import java.net.InetAddress

val cfg = UDP.Config()
cfg.codec = PacketCodec().doublesAsFloats().booleansAsInts()
val c = UDP.Client( InetAddress.getByName("10.0.17.5") -> 8000, cfg )

c.connect()
```

**Comment by evan108108** [comment]
Yes I have seen the link you provided above and I have added this flag

```
-Djava.net.preferIPv4Stack=true
```

to my "sbt" conf...

**Comment by Sciss** [comment]
So it works now? Trying on my machine with my local IP has no problem.

**Comment by evan108108** [comment]
No it is still not working...

**Comment by Sciss** [comment]
I'm afraid I can't help here. Are you sure that IP is reachable and the port is acceptable? `InetAddress.getByName("10.0.17.5").isReachable(1000) == true`?

**Comment by evan108108** [comment]
Its strange really. isReachable(1000) is returning false, however I am able to ping the IP from the console...

**Comment by evan108108** [comment]
Also I would like to note that I can send OSC messages via other means to this machine.

**Comment by evan108108** [comment]
I have tried a number of things and it seems that this is some kind of issue with my VM. I have run the same script directly on my local machine and this works perfectly. Thanks for your help. I anyone out there finds away to resolve this issue please let me know...
